version: 3.4

tasks:
  run:
    cmds:
      - npx ng serve -o

  fmt:
    cmds:
      - npx prettier --write .

  build:
    cmds:
      - npx ng build

  test:
    cmds:
      - npx ng test

  docker-build:
    sources:
      - ./public/**/*
      - ./src/**/*
      - package.json
      - package-lock.json
      - angular.json
      - Dockerfile
      - nginx.conf
    cmds:
      - docker build -t mapo-webapp .

  docker-run:
    cmds:
      - task: docker-build
      - |
        docker run \
          -p 4200:80 \
          mapo-webapp
