# This workflow will publish and deploy (PROD) any releases published. 
# ex:
# publish a release with a tag
name: mapo-webapp prod

# Event that triggers the workflow
on: 
  release:
    types: [published]

# This is required for requesting the JWT
permissions:
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # We need to checkout repo/code first
      - name: checkout code
        uses: actions/checkout@v2  

      - name: get tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: test tag
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
