# This workflow will publish and deploy to dev any changes pushed to main
# When doing a push to main or a PR we need to include a tag that is the new version of the project
# ex: 
# git tag 0.0.1
# git push origin 0.0.1

name: mapo-webapp deploy to dev

# Event that triggers the workflow
on: 
  push: 
    branches: [main]
    tags: ['*'] 
    
# This is required for requesting the JWT
permissions:
    id-token: write

# Executable part
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # We need to checkout repo/code first
    - name: checkout code
      uses: actions/checkout@v2  

    # We need to set up docker buildX
    - name: setup docker buildX
      uses: docker/setup-buildx-action@v3

    # We need to set up infisical secrets
    - name: get infisical secrets
      uses: Infisical/secrets-action@v1.0.7
      with:
          method: "oidc"
          env-slug: "dev"
          project-slug: "${{ secrets.INFISICAL_PROJECT_SLUG }}"
          identity-id: "${{ secrets.INFISICAL_IDENTITY_ID }}"

    # Make scripts executable
    - name: make scripts executable
      run: chmod +x ./packages/mapo-webapp-deploy/publish.sh ./packages/mapo-webapp-deploy/deploy.sh

    # Build and publish docker image
    - name: build and publish the docker image
      if: github.ref_type == 'tag'
      run: ./packages/mapo-webapp-deploy/publish.sh ${{ github.ref_name }}
      
    # Deploy to dev
    - name: deploy to dev VM
      if: github.ref_type == 'tag'
      run: ./packages/mapo-webapp-deploy/deploy.sh dev ${{ github.ref_name }}
